# Generated by Django 5.0.1 on 2024-07-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('ac_url', models.URLField(unique=True)),
                ('ac_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('ac_id', models.CharField(max_length=200, unique=True)),
                ('hl_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('ac_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_id', models.CharField(max_length=200, unique=True)),
                ('hl_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('ac_title', models.CharField(max_length=200)),
                ('ac_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_id', models.CharField(max_length=200, unique=True)),
                ('ac_json', models.JSONField()),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HLDealstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hl_id', models.CharField(max_length=200, unique=True)),
                ('hl_json', models.JSONField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HLPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hl_id', models.CharField(max_length=200, unique=True)),
                ('hl_json', models.JSONField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='sync.contact')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.customfield')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_id', models.CharField(max_length=200, unique=True)),
                ('hl_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('ac_json', models.JSONField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.contact')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.dealstage')),
            ],
        ),
        migrations.AddField(
            model_name='dealstage',
            name='hl_dealstage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.hldealstage'),
        ),
        migrations.AddField(
            model_name='hldealstage',
            name='hl_pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.hlpipeline'),
        ),
        migrations.CreateModel(
            name='PipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_id', models.CharField(max_length=200, unique=True)),
                ('ac_json', models.JSONField()),
                ('name', models.CharField(max_length=200)),
                ('hl_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.hlpipeline')),
            ],
        ),
        migrations.AddField(
            model_name='dealstage',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sync.pipeline'),
        ),
    ]
