# Generated by Django 5.0.1 on 2024-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
