# Generated by Django 5.0.1 on 2024-07-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_deal_created_date_deal_currency_deal_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealstage',
            name='ac_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
