# Generated by Django 5.0.1 on 2024-09-02 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_alter_deal_created_date_alter_deal_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('contacts_attempted', models.IntegerField(default=0)),
                ('contacts_synced', models.IntegerField(default=0)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
